version: "3.3"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '1235:1234'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules: